# Generated by Django 4.1.3 on 2022-11-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer_favorite_question_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='favorite',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
