# Generated by Django 4.1.3 on 2022-11-28 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_favorite_answer_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
