# Generated by Django 4.1.3 on 2022-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer_accepted'),
        ('api', '0005_rename_favorite_answer_favorites_and_more'),
    ]

    operations = [
    ]
