# Generated by Django 4.1.3 on 2022-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20221128_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='accepted',
        ),
    ]
