# Generated by Django 4.1.3 on 2022-11-28 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_question_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
