# Generated by Django 4.1.3 on 2022-11-30 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_question_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='question',
            name='favorites',
        ),
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
