# Generated by Django 4.1.3 on 2022-11-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_answer_accepted'),
        ('api', '0008_remove_answer_favorites_remove_question_favorites_and_more'),
    ]

    operations = [
    ]
